module.exports = {
  projects: [
    '<rootDir>/apps/ravepro',
    '<rootDir>/libs/ui',
    '<rootDir>/apps/api',
    '<rootDir>/libs/prisma',
    '<rootDir>/libs/containers',
    '<rootDir>/libs/utils',
    '<rootDir>/libs/chat',
    '<rootDir>/libs/chat-api',
    '<rootDir>/libs/community',
    '<rootDir>/libs/auth-api',
    '<rootDir>/libs/user-api',
    '<rootDir>/libs/connection-api',
    '<rootDir>/apps/pepega',
    '<rootDir>/libs/pepega-ui',
    '<rootDir>/apps/dream',
    '<rootDir>/libs/components',
    '<rootDir>/libs/icons',
  ],
};
